const jsonProducts = [
    {
        "name": "Vino",
        "stock": "30",
        "img": "https://www.espaciovino.com.ar/media/default/0001/62/thumb_61998_default_big.jpeg",
        "price": "3.142",
        "decription": "Rutini Malbec is very deep purplish red in color, the intense fruity aromas are intermingled with others typical of aging in new oak (vanilla, smoked, toasted). On the palate, its concentrated structure evokes its soft and sugary tannins.",
        "types": "vino",
        "brand": "Rutini",
        "calification": "0",
        "discount": "5",
        "origin": "Torre San Patrizio, Italia",
        "alcohol": "13,5",
    },
    {
        "name": "Vino",
        "stock": "25",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Luigi_Bosca_Malbec_vludvq.jpg",
        "price": "3.415",
        "decription": "Bottle 750cc, Intense ruby red colour. It presents aromas of ripe red fruits, spices and black pepper. The intensity of its entry into the mouth is complemented by the softness and sweetness of the tannins. A wine with great body and structure.",
        "types": "vino",
        "brand": "Luigi Bosca",
        "calification": "0",
        "discount": "5",
        "origin": "Luján de Cuyo, Mendoza.",
        "alcohol": "14",
    },
    {
        "name": "Vino",
        "stock": "40",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Punto_Final_Sauvignon_Blanc_d1bws7.jpg",
        "price": "3.184",
        "decription": "Bottle 750cc, Service temperature for this wine is between 8º and 10º C, Aging potential 3 years. Store in a cool, dark and vibration-free place. Ideal to accompany green leafy salads, sushi and seafood",
        "types": "vino",
        "brand": "Sauvignon",
        "calification": "0",
        "discount": "8",
        "origin": "Valle de Casablanca. Chile",
        "alcohol": "12,5",
    },
    {
        "name": "Vino",
        "stock": "40",
        "img": "https://www.espaciovino.com.ar/media/default/0001/54/thumb_53655_default_medium.jpeg",
        "price": "5.399",
        "decription": "Bottle 750cc,Wine with aromas of outstanding elegance and very good intensity, with golden flashes of high intensity.",
        "types": "vino",
        "brand": "Salentein",
        "calification": "0",
        "discount": "5",
        "origin": "Valle de Uco, Tunuyán. Provincia de Mendoza, Argentina.",
        "alcohol": "12 ",
    },
    {
        "name": "Vino",
        "stock": "79",
        "img": "https://cepadevinos.com/wp-content/uploads/2019/01/C9EsU4FXsAAFxCT.jpg",
        "price": "4.059",
        "decription": "Bottle 750cc, The best temperature to taste this wine is between 8° and 10° C. Recommended storage time 2 years. Ideal to pair with a fresh salad of green vegetables and seafood.",
        "types": "vino",
        "brand": "Alfredo Roca ",
        "calification": "0",
        "discount": "9",
        "origin": "San Rafael. Provincia de Mendoza, Argentina.",
        "alcohol": "12,5 ",
    },
    {
        "name": "Vino",
        "stock": "90",
        "img": "https://cepadevinos.com/wp-content/uploads/2016/09/Sin-lagarde.png",
        "price": "2.368",
        "decription": "Bottle 750cc, Service temperature for this wine is between 5º and 7º C, Aging potential 2 years. Store in a cool, dark place, and without vibrations. Ideal to accompany a rocket, grapefruit and parmesan salad. ",
        "types": "vino",
        "brand": "Lagarde",
        "calification": "0",
        "discount": "5",
        "origin": "Luján de Cuyo y Tupungato. Provincia de Mendoza, Argentina.",
        "alcohol": "13,2  ",
    },
    {
        "name": "Rosell Boher",
        "stock": "50",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Rosell_Boher_Ros%C3%A9_o6etmd.jpg",
        "price": "6.369",
        "decription": "Bottle 750cc, Service temperature for this wine is between 6º and 8º C, Aging potential 3 years. Store in a cool, dark and vibration-free place. Ideal to accompany a black olive Focaccia.",
        "types": "cerveza",
        "brand": " Rosell Boher",
        "calification": "0",
        "discount": "10",
        "origin": "Valle de Uco, Provincia de Mendoza, Argentina.",
        "alcohol": "13",
    },
    {
        "name": "Cruzat Cuvée Reserve Extra Brut",
        "stock": "60",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Cruzat_Cuv%C3%A9e_Reserve_Extra_Brut_krrmgn.jpg",
        "price": "3.710",
        "decription": "Bottle 750cc, Service temperature of this sparkling wine is between 6º and 8º C, Aging potential 3 years. Ideal to enjoy with shellfish and fish with consistent sauces, white meats with light sauces, pasta and roasted or grilled meats.",
        "types": "cerveza",
        "brand": "Cruzat Larrain ",
        "calification": "0",
        "discount": "5",
        "origin": "Tupungato, Valle de Uco. Provincia de Mendoza, Argentina.",
        "alcohol": "13",
    },
    {
        "name": "Johnnie Walker Black Label",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2018/03/Johnnie-Walker-Black-Label-750cc..jpg",
        "price": "12.000",
        "decription": "Bottle 750cc, 492 / 5,000 Resultados de traducción  Traducción Johnnie Walker Black is the most recognized and awarded luxury whiskey. It is considered by experts to be an iconic blend, a benchmark by which all other whiskeys are measured. Only whiskeys with at least 12 years of age are included in the blend, giving it a unique complexity and depth. Perfectly balanced with intense flavors from the 4 corners of Scotland. It has notes of fresh and ripe fruit, with a smoky background leaving subtle traces of vanilla and spices.",
        "types": "whisky",
        "brand": "Johnnie Walker",
        "calification": "0",
        "discount": "20",
        "origin": "Kilmarnock, Escocia.",
        "alcohol": "30",
    },
    {
        "name": "Johnnie Walker Red Label",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Johnnie_Walker_Red_Label_yrxiis.jpg",
        "price": "12.000",
        "decription": "Bottle 1.000cc, Johnnie Walker Red is the most consumed blend of whiskeys in the world. Over a century winning prizes and awards, helping to define the world of Whiskeys. Its flavor is the most vibrant and versatile of the Johnnie Walker range. It seduces with its intense aromas of fresh fruits, spices and slight smoky notes.",
        "types": "whisky",
        "brand": "Johnnie Walker",
        "calification": "0",
        "discount": "20",
        "origin": "Kilmarnock, Escocia.",
        "alcohol": "30",
    },
    {
        "name": "Jameson Irish Whiskey",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2018/03/Johnnie-Walker-Black-Label-750cc..jpg",
        "price": "5.169",
        "decription": "Bottle 750cc, Warm golden colour. Aroma Soft and fragrant, with notes of toasted wood and sherry. Its flavor is exceptionally smooth, sweet and complex. Delicate fusion of flavors such as vanilla, oak, honey, complemented by spices, caramel and nuts. Delicate finish and persistent on the palate. Its greater smoothness is due to its triple distillation.",
        "types": "whisky",
        "brand": "Jameson",
        "calification": "0",
        "discount": "4",
        "origin": "Irlanda",
        "alcohol": "40 ",
    },
    {
        "name": "Gordon's",
        "stock": "60",
        "img": "https://www.vinosyspirits.com/media/catalog/product/g/o/gordons-botella_685x1200_1.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:",
        "price": "3.313",
        "decription": "Bottle 750cc, Gordon's is one of the oldest gins, created in 1769, and was one of the first to be taken with tonic. Today Gordon's is the best-selling London Dry gin in the world, a bottle of Gordon's is sold every 6 seconds. More than 3,000 juniper berries are nose-tested and 95% are rejected to ensure that only the best are in our gin, creating a liquid of the highest quality.",
        "types": "ron",
        "brand": "	Gordon's",
        "calification": "8.5",
        "discount": "10",
        "origin": "	Reino Unido",
        "alcohol": "38 ",
    },
    {
        "name": "Bulldog",
        "stock": "60",
        "img": "https://cepadevinos.com/wp-content/uploads/2020/08/gin-Buldos.png",
        "price": "8.500",
        "decription": "Bottle 700 cc, In the mouth, Bulldog gin offers us many very pleasant floral, fruit and citrus notes. The perfect integration of juniper is surprising, which is not hidden in the symphony of flavors it offers us. In successive sips notes of lychee and lavender appear.",
        "types": "ron",
        "brand": "Campari",
        "calification": "0",
        "discount": "18",
        "origin": "	Reino Unido",
        "alcohol": "40 ",
    },
    {
        "name": "Hendricks",
        "stock": "60",
        "img": "https://cepadevinos.com/wp-content/uploads/2018/03/Gin-Hendrix.jpg",
        "price": "15.000",
        "decription": "Bottle 700 cc, In the mouth, HENDRICK'S is the union of TWO DIFFERENT SPIRITS from two different STILLS: The Bennett Still and the Carter-Head Still. By combining the two, we can create an extraordinarily smooth gin that has the necessary character and a balance of subtle flavors.",
        "types": "ron",
        "brand": "hendriks",
        "calification": "0",
        "discount": "20",
        "origin": "	 Girvan, Escocia",
        "alcohol": "35 ",
    },
]

module.exports = jsonProducts;