const jsonProducts = [
    {
        "name": "Rutini Cabernet Malbec",
        "stock": "30",
        "img": "https://www.espaciovino.com.ar/media/default/0001/62/thumb_61998_default_big.jpeg",
        "price": "3.142",
        "decription": "Rutini Malbec is very deep purplish red in color, the intense fruity aromas are intermingled with others typical of aging in new oak (vanilla, smoked, toasted). On the palate, its concentrated structure evokes its soft and sugary tannins.",
        "types": "tinto",
        "brand": "Rutini",
        "comments": "Excelente",
        "calification": "10",
        "discount": "5",
        "origin": "Torre San Patrizio, Italia",
        "alcohol": "13,5",
        "type": "tinto"
    },
    {
        "name": "Luigi Bosca Malbec",
        "stock": "25",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Luigi_Bosca_Malbec_vludvq.jpg",
        "price": "3.415",
        "decription": "Bottle 750cc, Intense ruby red colour. It presents aromas of ripe red fruits, spices and black pepper. The intensity of its entry into the mouth is complemented by the softness and sweetness of the tannins. A wine with great body and structure.",
        "types": "tinto",
        "brand": "Luigi Bosca",
        "comments": "Excelente",
        "calification": "10",
        "discount": "5",
        "origin": "Luján de Cuyo, Mendoza.",
        "alcohol": "14",
        "type": "tinto"
    },
    {
        "name": "Punto Final Sauvignon Blanc",
        "stock": "40",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Punto_Final_Sauvignon_Blanc_d1bws7.jpg",
        "price": "3.184",
        "decription": "Bottle 750cc, Service temperature for this wine is between 8º and 10º C, Aging potential 3 years. Store in a cool, dark and vibration-free place. Ideal to accompany green leafy salads, sushi and seafood",
        "types": "blanco",
        "brand": "Sauvignon",
        "comments": "Excelente",
        "calification": "9",
        "discount": "8",
        "origin": "Valle de Casablanca. Chile",
        "alcohol": "12,5",
        "type": "blanco"
    },
    {
        "name": "Salentein Primus Chardonnay",
        "stock": "40",
        "img": "https://www.espaciovino.com.ar/media/default/0001/54/thumb_53655_default_medium.jpeg",
        "price": "5.399",
        "decription": "Bottle 750cc,Wine with aromas of outstanding elegance and very good intensity, with golden flashes of high intensity.",
        "types": "blanco",
        "brand": "Salentein",
        "comments": "8.7",
        "calification": "10",
        "discount": "5",
        "origin": "Valle de Uco, Tunuyán. Provincia de Mendoza, Argentina.",
        "alcohol": "12 ",
        "type": "blanco"
    },
    {
        "name": "Alfredo Roca Nuri Rosado",
        "stock": "79",
        "img": "https://cepadevinos.com/wp-content/uploads/2019/01/C9EsU4FXsAAFxCT.jpg",
        "price": "4.059",
        "decription": "Bottle 750cc, The best temperature to taste this wine is between 8° and 10° C. Recommended storage time 2 years. Ideal to pair with a fresh salad of green vegetables and seafood.",
        "types": "rosado",
        "brand": "Alfredo Roca ",
        "comments": "311 / 5,000 Resultados de traducción Traducción To do this, we worked under a controlled atmosphere and at low temperatures to avoid oxidation. After a slight cold maceration of the skins before pressing, the free-drained juice was fermented at a temperature of 13º C. Its permanence on fine lees for 3 months gives it expression and structure.",
        "calification": "10",
        "discount": "9",
        "origin": "San Rafael. Provincia de Mendoza, Argentina.",
        "alcohol": "12,5 ",
        "type": "rosado"
    },
    {
        "name": "Lagarde Goes pink Rose",
        "stock": "90",
        "img": "https://cepadevinos.com/wp-content/uploads/2016/09/Sin-lagarde.png",
        "price": "2.368",
        "decription": "Bottle 750cc, Service temperature for this wine is between 5º and 7º C, Aging potential 2 years. Store in a cool, dark place, and without vibrations. Ideal to accompany a rocket, grapefruit and parmesan salad. ",
        "types": "rosado",
        "brand": "Lagarde",
        "comments": "311 / 5,000 Resultados de traducción Traducción To do this, we worked under a controlled atmosphere and at low temperatures to avoid oxidation. After a slight cold maceration of the skins before pressing, the free-drained juice was fermented at a temperature of 13º C. Its permanence on fine lees for 3 months gives it expression and structure.",
        "calification": "8.5",
        "discount": "5",
        "origin": "Luján de Cuyo y Tupungato. Provincia de Mendoza, Argentina.",
        "alcohol": "13,2  ",
        "type": "rosado"
    },
]