const jsonProducts = [
    {
        "name": "BenMarco Malbec",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/BenMarco_Malbec_tofq1r.jpg",
        "price": "3300",
        "description": "Bottle 750cc, Service temperature of this wine is between 16º and 18º C, Aging potential 4 years. Decant for an hour before drinking. Store in a cool, dark place, and without vibrations. Ideal to accompany a roasted Faizan with mustard sambayon and glazed carrots.",
        "types": "vino",
        "brand": "Dominio del Plata",
        "calification": "0",
        "discount": "18",
        "origin": "Argentina",
        "alcohol": "14",
    },
    {
        "name": "Los Cardos Malbec",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2016/09/loscardos.jpg",
        "price": "1600",
        "description": "Bottle 750cc, The harvest is done from the middle to the end of March. The grapes are destemmed with soft grain breakage. Pre-fermentative cold maceration is carried out to preserve primary aromas. Then the must is cooled and traditional fermentation is carried out. Post-fermentative maceration lasts between 10 and 15 days. Malolactic fermentation takes place after maceration..",
        "types": "vino",
        "brand": "Doña Paula",
        "calification": "0",
        "discount": "40",
        "origin": "Argentina",
        "alcohol": "14 ",
    },
    {
        "name": "Escorihuela Gascon Malbec",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Escorihuela_Gascon_Malbec_vfmwya.jpg",
        "price": "3200",
        "description": "Bottle 750cc, Aged 8 months in barrels. 50% French oak, 50% American oak. Harvest By hand and fermentation in stainless steel tanks, barely destemmed, a pre-fermentative maceration is carried out at 10º C for 72 hours. Then the alcoholic fermentation is conducted making a peak of 28º maximum, ending at a temperature of 23-24º C to obtain all the fruity aromas.",
        "types": "vino",
        "brand": "Escorihuela Gascon",
        "calification": "0",
        "discount": "40",
        "origin": "Argentina",
        "alcohol": "14 ",
    },
    {
        "name": "Trumpeter Cabernet",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Trumpeter_Cabernet_Sauvignon_ns62ut.jpg",
        "price": "3407",
        "description": "Bottle 750cc,Intense ruby, with violet tones. On the nose, it displays concentrated aromas of red fruit, finely mixed with others contributed by the oak (cocoa, tobacco, vanilla). Its smooth profile reveals flavors that evoke ripe plums and black cherries, leaving a full and sustained finish on the palate..",
        "types": "vino",
        "brand": "La Rural",
        "calification": "0",
        "discount": "40",
        "origin": "Argentina",
        "alcohol": "13",
    },
    {
        "name": "Salentein Reserve Merlot",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Salentein_Reserve_Merlot_sndhhr.jpg",
        "price": "2999",
        "description": "Bottle 750cc,10 to 12 months in French oak barrels. Varietals from farms that are located between 1,050 and 1,700 meters, with stony soils, wide thermal amplitude, optimal sun exposure and pure meltwater from the Andes that provide the ideal conditions for making wines that are the maximum expression of the Valle de uco.",
        "types": "vino",
        "brand": "Salentein",
        "calification": "0",
        "discount": "40",
        "origin": "Argentina",
        "alcohol": "14",
    },
    {
        "name": "Rutini Malbec",
        "stock": "30",
        "img": "https://www.espaciovino.com.ar/media/default/0001/62/thumb_61998_default_big.jpeg",
        "price": "3142",
        "description": "Rutini Malbec is very deep purplish red in color, the intense fruity aromas are intermingled with others typical of aging in new oak (vanilla, smoked, toasted). On the palate, its concentrated structure evokes its soft and sugary tannins.",
        "types": "vino",
        "brand": "Rutini",
        "calification": "0",
        "discount": "5",
        "origin": "Italia",
        "alcohol": "13.5",
    },
    {
        "name": "Luigi Bosca",
        "stock": "25",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Luigi_Bosca_Malbec_vludvq.jpg",
        "price": "3415",
        "description": "Bottle 750cc, Intense ruby red colour. It presents aromas of ripe red fruits, spices and black pepper. The intensity of its entry into the mouth is complemented by the softness and sweetness of the tannins. A wine with great body and structure.",
        "types": "vino",
        "brand": "Luigi Bosca",
        "calification": "0",
        "discount": "5",
        "origin": "Argentina",
        "alcohol": "14.00",
    },
    {
        "name": "Sauvignon",
        "stock": "40",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Punto_Final_Sauvignon_Blanc_d1bws7.jpg",
        "price": "3184",
        "description": "Bottle 750cc, Service temperature for this wine is between 8º and 10º C, Aging potential 3 years. Store in a cool, dark and vibration-free place. Ideal to accompany green leafy salads, sushi and seafood",
        "types": "vino",
        "brand": "Sauvignon",
        "calification": "0",
        "discount": "8",
        "origin": "Chile",
        "alcohol": "12.5",
    },
    {
        "name": "Salentein",
        "stock": "40",
        "img": "https://www.espaciovino.com.ar/media/default/0001/54/thumb_53655_default_medium.jpeg",
        "price": "5399",
        "description": "Bottle 750cc,Wine with aromas of outstanding elegance and very good intensity, with golden flashes of high intensity.",
        "types": "vino",
        "brand": "Salentein",
        "calification": "0",
        "discount": "5",
        "origin": "Argentina",
        "alcohol": "5.00",
    },
    {
        "name": "Alfredo Roca",
        "stock": "79",
        "img": "https://cepadevinos.com/wp-content/uploads/2019/01/C9EsU4FXsAAFxCT.jpg",
        "price": "4059",
        "description": "Bottle 750cc, The best temperature to taste this wine is between 8° and 10° C. Recommended storage time 2 years. Ideal to pair with a fresh salad of green vegetables and seafood.",
        "types": "vino",
        "brand": "Alfredo Roca ",
        "calification": "0",
        "discount": "9",
        "origin": "Argentina",
        "alcohol": "12.5 ",
    },
    {
        "name": "Lagarde",
        "stock": "90",
        "img": "https://cepadevinos.com/wp-content/uploads/2016/09/Sin-lagarde.png",
        "price": "2368",
        "description": "Bottle 750cc, Service temperature for this wine is between 5º and 7º C, Aging potential 2 years. Store in a cool, dark place, and without vibrations. Ideal to accompany a rocket, grapefruit and parmesan salad. ",
        "types": "vino",
        "brand": "Lagarde",
        "calification": "0",
        "discount": "5",
        "origin": "Argentina",
        "alcohol": "13.2  ",
    },
    {
        "name": "Rosell Boher",
        "stock": "50",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Rosell_Boher_Ros%C3%A9_o6etmd.jpg",
        "price": "6369",
        "description": "Bottle 750cc, Service temperature for this wine is between 6º and 8º C, Aging potential 3 years. Store in a cool, dark and vibration-free place. Ideal to accompany a black olive Focaccia.",
        "types": "espumante",
        "brand": " Rosell Boher",
        "calification": "0",
        "discount": "10",
        "origin": "Argentina",
        "alcohol": "1.3",
    },
    {
        "name": "Cruzat Premier Rosé Extra",
        "stock": "60",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Cruzat_Cl%C3%A1sico_Ros%C3%A9_Extra_Brut_djgn6g.jpg",
        "price": "3600",
        "description": "Bottle 750cc, The Chardonnay must is extracted with a pneumatic press in a single pressing process. Pinot Noir is gently pressed with the presence of CO2. The contact of the must with the skin of the grape, produces the carbonic maceration, gently yielding color and distinctive aromas of the Rosé. This process lasts approximately 8 hours. and ends with tasting. Then the must is cooled to 2ºC for 24 hours to cause sedimentation of impurities.",
        "types": "espumante",
        "brand": "Cruzat Larrain",
        "calification": "0",
        "discount": "30",
        "origin": "Argentina",
        "alcohol": "11.8 ",
    },
    {
        "name": "Cruzat Cuvée Reserve",
        "stock": "60",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Cruzat_Cuv%C3%A9e_Reserve_Extra_Brut_krrmgn.jpg",
        "price": "3710",
        "description": "Bottle 750cc, Service temperature of this sparkling wine is between 6º and 8º C, Aging potential 3 years. Ideal to enjoy with shellfish and fish with consistent sauces, white meats with light sauces, pasta and roasted or grilled meats.",
        "types": "espumante", 
        "brand": "Cruzat Larrain ",
        "calification": "0",
        "discount": "5",
        "origin": "Argentina",
        "alcohol": "1.3",
    },
    {
        "name": "Sylvestra Rosé Brut Nature",
        "stock": "60",
        "img": "https://cepadevinos.com/wp-content/uploads/2018/01/Sylvestra-Brut-Nature-Rose-600x600.jpg",
        "price": "5500",
        "description": "Bottle 750cc, Color: Salmon pink with light reflections.",
        "types": "espumante",
        "brand": "Bressia",
        "calification": "0",
        "discount": "29",
        "alcohol": "11.6",
    },
    {
        "name": "J & B",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2018/03/J-B-750cc..jpg",
        "price": "4900",
        "description": "Bottle 750cc, The world's first selectively aged* Scotch whiskey in Japanese Mizunara oak barrels. Chivas Mizunara is the perfect fusion of Scottish art with Japanese tradition, resulting in an incredibly sophisticated blend. A wonderful whiskey with a touch of spices. Because success is in the mix, both in life and in Scotland.",
        "types": "whisky",
        "brand": "J & B",
        "calification": "0",
        "discount": "27",
        "origin": "Escocia",
        "alcohol": "40 ",
    },
    {
        "name": "Chivas Mizunara",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2021/09/be73145.jpg",
        "price": "18000",
        "description": "Bottle 1000cc, The world's first selectively aged* Scotch whiskey in Japanese Mizunara oak barrels. Chivas Mizunara is the perfect fusion of Scottish art with Japanese tradition, resulting in an incredibly sophisticated blend. A wonderful whiskey with a touch of spices. Because success is in the mix, both in life and in Scotland.",
        "types": "whisky",
        "brand": "Chivas",
        "calification": "0",
        "discount": "27",
        "origin": "Escocia",
        "alcohol": "40 ",
    },
    {
        "name": "White Horse",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2019/04/whitehorse.jpg",
        "price": "3000",
        "description": "Bottle 1000cc, Good balance and complexity, with notes of oak, smoke and caramel. There is a good fruity note, with the presence of malt..",
        "types": "whisky",
        "brand": "White Horse",
        "calification": "0",
        "discount": "27",
        "origin": "Escocia",
        "alcohol": "40",
    },
    {
        "name": "Chivas 12 años",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2018/01/Chivas-12-a%C3%B1os-1000cc..jpg",
        "price": "14000",
        "description": "Bottle 1000cc, Chivas 12 contains only the best single malt and grain whiskeys. Within the 12-year-old Scotches that are part of this distinctive blend you will find Strathisla single malt and Strathclyde grain single, among others, to create an extraordinarily smooth whiskey.",
        "types": "whisky",
        "brand": "Chivas",
        "calification": "0",
        "discount": "31",
        "origin": "Escocia",
        "alcohol": "40",
    },
    {
        "name": "Johnnie Walker Black Label",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2018/03/Johnnie-Walker-Black-Label-750cc..jpg",
        "price": "12000",
        "description": "Bottle 750cc, 492 / 5,000 Resultados de traducción  Traducción Johnnie Walker Black is the most recognized and awarded luxury whiskey. It is considered by experts to be an iconic blend, a benchmark by which all other whiskeys are measured. Only whiskeys with at least 12 years of age are included in the blend, giving it a unique complexity and depth. Perfectly balanced with intense flavors from the 4 corners of Scotland. It has notes of fresh and ripe fruit, with a smoky background leaving subtle traces of vanilla and spices.",
        "types": "whisky",
        "brand": "Johnnie Walker",
        "calification": "0",
        "discount": "20",
        "origin": "Escocia",
        "alcohol": "3.0",
    },
    {
        "name": "Johnnie Walker Red Label",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Johnnie_Walker_Red_Label_yrxiis.jpg",
        "price": "12000",
        "description": "Bottle 1.000cc, Johnnie Walker Red is the most consumed blend of whiskeys in the world. Over a century winning prizes and awards, helping to define the world of Whiskeys. Its flavor is the most vibrant and versatile of the Johnnie Walker range. It seduces with its intense aromas of fresh fruits, spices and slight smoky notes.",
        "types": "whisky",
        "brand": "Johnnie Walker",
        "calification": "0",
        "discount": "20",
        "origin": "Escocia",
        "alcohol": "3.0",
    },
    {
        "name": "Jameson Irish Whiskey",
        "stock": "70",
        "img": "https://cepadevinos.com/wp-content/uploads/2018/03/Johnnie-Walker-Black-Label-750cc..jpg",
        "price": "5169",
        "description": "Bottle 750cc, Warm golden colour. Aroma Soft and fragrant, with notes of toasted wood and sherry. Its flavor is exceptionally smooth, sweet and complex. Delicate fusion of flavors such as vanilla, oak, honey, complemented by spices, caramel and nuts. Delicate finish and persistent on the palate. Its greater smoothness is due to its triple distillation.",
        "types": "whisky",
        "brand": "Jameson",
        "calification": "0",
        "discount": "4",
        "origin": "Irlanda",
        "alcohol": "4.0",
    },
    {
        "name": "Havana Club 7 Años ",
        "stock": "60",
        "img": "https://www.espaciovino.com.ar/media/default/0001/55/thumb_54776_default_big.jpeg",
        "price": "8912 ",
        "description": "Bottle 750 cc, Havana Club 7 Years Rum is the epitome of Cuban Rum. It is a legendary rum that reinforces Cuba's place as the cradle of the finest rums. Within the Club Havana variety, the 7-year-old encompasses all the distinctive flavors, richness, and wisdom that make Havana Club famous.",
        "types": "ron",
        "brand": "Havana",
        "calification": "0",
        "discount": "10",
        "origin": "Cuba",
        "alcohol": "40",
    },
    {
        "name": "Negrita Dorado ",
        "stock": "60",
        "img": "https://www.espaciovino.com.ar/media/default/0001/55/thumb_54572_default_big.jpeg",
        "price": "4350 ",
        "description": "Bottle 700 cc, Since 1857, the distillery's experienced masters have passionately aged and blended the finest rums in the Caribbean. Each one contributing its aromas, its bouquet and delicacy. This is how Negrita was born, whose golden version is the rum in gastronomic circles par excellence.",
        "types": "ron",
        "brand": "Bardinet",
        "calification": "0",
        "discount": "10",
        "origin": "Francia",
        "alcohol": "37.5",
    },
    {
        "name": "Malibu ",
        "stock": "60",
        "img": "https://www.espaciovino.com.ar/media/default/0001/55/thumb_54563_default_big.jpeg",
        "price": "4350 ",
        "description": "Bottle 700 cc, Malibu is smooth and delicate, with subtle hints of sugar cane and butter. Smooth and natural coconut rum with a light body.",
        "types": "ron",
        "brand": "Malibu",
        "calification": "0",
        "discount": "10",
        "origin": "Brasil",
        "alcohol": "15",
    },
    {
        "name": "Flor de Caña Añejo Oro ",
        "stock": "60",
        "img": "https://www.espaciovino.com.ar/media/default/0001/54/thumb_53426_default_big.jpeg",
        "price": "4350 ",
        "description": "Bottle 750  cc, A soft attack gives way to a round, dry, medium-bodied palate with flavors of caramel, sugar cane and spicy spice flavors. It ends with a touch of toasted coconut and pepper. Very clean and pure, this traditional rum aged for 4 years, is distinguished by its medium body.",
        "types": "ron",
        "brand": "Flor de Caña",
        "calification": "0",
        "discount": "10",
        "origin": "Nicaragua",
        "alcohol": "40",
    },
    {
        "name": "Appleton Estate Extra",
        "stock": "60",
        "img": "https://www.espaciovino.com.ar/media/default/0001/68/thumb_67693_default_big.jpeg",
        "price": "12534 ",
        "description": "Bottle 750  cc, Ripe aromas of walnuts, nutmeg, orange peel and vanilla. Subtle touch of coffee and cocoa, toasted oak and almond. Mouth: buttery, sugar. Finish: Bittersweet and delicious.",
        "types": "ron",
        "brand": "Appleton Estate",
        "calification": "0",
        "discount": "10",
        "origin": "Jamaica",
        "alcohol": "40",
    },
    {
        "name": "Flor de Caña Blanco ",
        "stock": "60",
        "img": "https://www.espaciovino.com.ar/media/default/0001/55/thumb_54875_default_big.jpeg",
        "price": "4290  ",
        "description": "Bottle 750  cc, Palate: A soft and round entry gives way to a subtle, dry medium-bodied palate with a flavor of vanilla, coconut and a touch of Bourbon barrel spices. It ends with a long taste of dried sugar cane and roasted vanilla.",
        "types": "ron",
        "brand": "Flor de Caña",
        "calification": "0",
        "discount": "10",
        "origin": "Nicaragua",
        "alcohol": "40",
    },
    {
        "name": "Bacardi Carta Oro ",
        "stock": "60",
        "img": "https://www.espaciovino.com.ar/media/default/0001/58/thumb_57908_default_big.jpeg",
        "price": "3833",
        "description": "Bottle 980 cc, Bacardi Gold is the world's first light gold rum. It is aged in white oak barrels toasted over the fire to give it character, subsequently subjecting it to filtration until it achieves its characteristic softness.",
        "types": "ron",
        "brand": "Bacardi",
        "calification": "0",
        "discount": "10",
        "origin": "Puerto Rico",
        "alcohol": "37.5",
    },
    {
        "name": "Bacardi Carta Blanca",
        "stock": "60",
        "img": "https://www.espaciovino.com.ar/media/default/0001/58/thumb_57909_default_big.jpeg",
        "price": "3833",
        "description": "Bottle 980 cc, Bacardi Superior Rum presents notes of vanilla and almond that are intensified by the oak barrels, as well as a unique smoothness by the mixture with charcoal..",
        "types": "ron",
        "brand": "	Bacardi",
        "calification": "0",
        "discount": "10",
        "origin": "Puerto Rico",
        "alcohol": "37.5",
    },
    {
        "name": "Havana Club Añejo",
        "stock": "60",
        "img": "https://www.espaciovino.com.ar/media/default/0001/55/thumb_54777_default_big.jpeg",
        "price": "3920",
        "description": "Bottle 750cc,Havana Club Añejo Especial is a first-class golden rum, a blend of rums aged for five years in aging ships, under the watchful eye of Maestro Ronero, Don José Navarro. As the name suggests, this is something special, a blend of aged and young rums resulting in a warm, rich, golden-hued rum. Its character combines the lightness of white rums and the robust aroma of dark rums.",
        "types": "ron",
        "brand": "	Havana",
        "calification": "0",
        "discount": "10",
        "origin": "Cuba",
        "alcohol": "40",
    },
    {
        "name": "Gordon's",
        "stock": "60",
        "img": "https://www.vinosyspirits.com/media/catalog/product/g/o/gordons-botella_685x1200_1.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:",
        "price": "3313",
        "description": "Bottle 750cc, Gordon's is one of the oldest gins, created in 1769, and was one of the first to be taken with tonic. Today Gordon's is the best-selling London Dry gin in the world, a bottle of Gordon's is sold every 6 seconds. More than 3,000 juniper berries are nose-tested and 95% are rejected to ensure that only the best are in our gin, creating a liquid of the highest quality.",
        "types": "ron",
        "brand": "	Gordon's",
        "calification": "0",
        "discount": "10",
        "origin": "Reino Unido",
        "alcohol": "3.8",
    },
    {
        "name": "Bulldog",
        "stock": "60",
        "img": "https://cepadevinos.com/wp-content/uploads/2020/08/gin-Buldos.png",
        "price": "8500",
        "description": "Bottle 700 cc, In the mouth, Bulldog gin offers us many very pleasant floral, fruit and citrus notes. The perfect integration of juniper is surprising, which is not hidden in the symphony of flavors it offers us. In successive sips notes of lychee and lavender appear.",
        "types": "ron",
        "brand": "Campari",
        "calification": "0",
        "discount": "18",
        "origin": "Reino Unido",
        "alcohol": "4.0",
    },
    {
        "name": "Hendricks",
        "stock": "60",
        "img": "https://cepadevinos.com/wp-content/uploads/2018/03/Gin-Hendrix.jpg",
        "price": "15000",
        "description": "Bottle 700 cc, In the mouth, HENDRICK'S is the union of TWO DIFFERENT SPIRITS from two different STILLS: The Bennett Still and the Carter-Head Still. By combining the two, we can create an extraordinarily smooth gin that has the necessary character and a balance of subtle flavors.",
        "types": "ron",
        "brand": "hendriks",
        "calification": "0",
        "discount": "20",
        "origin": "Escocia",
        "alcohol": "3.5 ",
    },
    {
        "name": "Patagonia 24.7",
        "stock": "100",
        "img": "https://cepadevinos.com/wp-content/uploads/2022/04/patagonia.jpg",
        "price": "520",
        "description": "Bottle 355 cc,Session IPA style beer, very drinkable and refreshing, with marked bitterness provided by a combination of Patagonian hops. It has an intense aroma of citrus and fruit thanks to the technique of adding cold hops called Dry Hopping. The addition of elderberry and cold honey balance the bitterness of the hops, providing some acidity and a dry finish. Perfect combination with fruit dishes, sweet and sour salads and Thai food. Meals with not much intensity of flavor or fat, but aromatic and spicy. Scented risottos, cheesecake.",
        "types": "cerveza",
        "brand": "Patagonia",
        "calification": "0",
        "discount": "20",
        "origin": "Argentina",
        "alcohol": "4.8",
    },
    {
        "name": "Corona Botella",
        "stock": "150",
        "img": "https://cepadevinos.com/wp-content/uploads/2021/02/corona-330cc.png",
        "price": "420",
        "description": "Bottle 330 cc, Corona is a premium, classic and authentic beer, recognized worldwide for its high quality, distinctive flavor and image. It is a beer that transmits tranquility and relaxation, inviting consumers to disconnect from everyday life through pleasant experiences.",
        "types": "cerveza",
        "brand": "Corona",
        "calification": "0",
        "discount": "20",
        "origin": "Mexico",
        "alcohol": "4.5",
    },
    {
        "name": "Patagonia Amber Lager",
        "stock": "150",
        "img": "https://cepadevinos.com/wp-content/uploads/2022/04/patagonia.jpg",
        "price": "500",
        "description": "Bottle 410 cc, In Patagonia Amber Lager you will find a beer with a soft caramel flavor, made with a combination of 4 malts, which give it its characteristic amber color and malty flavor, leaving a subtle sweetness in the mouth. The flavor of caramelization of malts can remind us of flavors of caramelized onions, sweet and sour sauces, caramel sauces in creamy desserts. Other infallible dishes are grilled red meat, hamburgers, and roasted sweet potatoes. Its subtle sweet flavor makes it perfect to accompany sweet and sour dishes.",
        "types": "cerveza",
        "brand": "Patagonia",
        "calification": "0",
        "discount": "24",
        "origin": "Argentina",
        "alcohol": "4.5",
    },
    {
        "name": " Andes Origen Rubia ",
        "stock": "150",
        "img": "https://http2.mlstatic.com/D_NQ_NP_2X_758130-MLA44839765132_022021-F.webp",
        "price": "438",
        "description": "Bottle 473 cc, Andes Origen rescues the pleasure of the moment. A beer designed for those people who value their free time, for those who enjoy the little moments in life. The ideal option for those who want to pamper themselves. The Andes Origen Rubia is an American pilsner style beer, a Blonde with body and malt character. Slight aroma of hops, cereal and hint of yeast. It should be served in a glass to better appreciate its aromas and thus highlight its bright golden color. The Andes Origen Rubia is a delightful beer, but refreshing at the same time. It goes very well with pork or red meat made with flavored sauces, spicy dressings such as mustard, mild honey and herbs such as thyme or rosemary.",
        "types": "cerveza",
        "brand": "Andes ",
        "calification": "0",
        "discount": "24",
        "origin": "Argentina",
        "alcohol": "4.8",
    },
    {
        "name": " Michelob Ultra ",
        "stock": "150",
        "img": "https://cepadevinos.com/wp-content/uploads/2021/08/micheloblata_grande1121.png",
        "price": "530",
        "description": "Bottle 410 cc, 305 / 5,000 Resultados de traducción Traducción Michelob Ultra, launched in 2002 in the United States, is one of the lowest calorie beers in the world of beer! At just 91 calories (40% less than a regular beer) and 2.8 carbs, Michelob Ultra is the perfect beer for those seeking a balance between their active and social lives.",
        "types": "cerveza",
        "brand": "Michelob",
        "calification": "0",
        "discount": "24",
        "origin": "Argentina",
        "alcohol": "3.5",
    },
    {
        "name": " Andes Origen Roja ",
        "stock": "150",
        "img": "https://cepadevinos.com/wp-content/uploads/2021/01/133-1.jpg",
        "price": "420",
        "description": "Bottle 473 CC, Andes Origen Roja a is a beer that has a dry finish and a slight acidity that make it very versatile. It is a Vienna Lager style beer, its aroma of soft caramel and slight hops achieve a perfect balance. The Andes Red origin, copper amber color, is a beer of delight. Ideal to accompany fish or red meat, made with fresh or grilled vegetables.s.",
        "types": "cerveza",
        "brand": "Andes ",
        "calification": "0",
        "discount": "24",
        "origin": "Argentina",
        "alcohol": "4.9",
    },
    {
        "name": " Andes Origen IPA ",
        "stock": "150",
        "img": "https://cepadevinos.com/wp-content/uploads/2021/01/12463.jpg",
        "price": "500",
        "description": "Bottle 410CC , Andes IPA Andina is an IPA-style beer, worth the redundancy, from the English school. As you surely know, this style of beer is characterized by the bitterness that its high hop content gives it. What you probably don't know is that the Andean IPA contains Mendoza grapes.",
        "types": "cerveza",
        "brand": "Andes ",
        "calification": "0",
        "discount": "30",
        "origin": "Argentina",
        "alcohol": "4.5",
    },
    {
        "name": "Patagonia Bohemian",
        "stock": "150",
        "img": "https://cepadevinos.com/wp-content/uploads/2021/01/1bohemian_pilsener-1000x1647_1024x102421-84eeae85b298cc386b15878702052033-1024-1024.png",
        "price": "455",
        "description": "Bottle 473 CC, Patagonia Bohemian Pilsener is a beer characterized by its bright golden color and malty aroma, like bread. It is ideal for white meats, such as chicken and fish with herbal sauces. Wok dishes and chicken sandwiches are great allies for this beer. By contrast, we can also pair it with slightly acidic dishes, such as sauces with tomatoes and other vegetables. 🏅 She was the winner of her style (Czech-style Pale) at the World Beer Awars 2019",
        "types": "cerveza",
        "brand": "Patagonia",
        "calification": "0",
        "discount": "30",
        "origin": "Argentina",
        "alcohol": "4.5",
    },
    {
        "name": "Andes Origen Negra",
        "stock": "150",
        "img": "https://http2.mlstatic.com/D_NQ_NP_2X_673031-MLA44839749297_022021-F.webp",
        "price": "400",
        "description": "Bottle 473 CC, Andes Origen rescues the pleasure of the moment. A beer designed for those people who value their free time, for those who enjoy the little moments in life. The ideal option for those who want to pamper themselves. Andes Negra is a German Schwarzbier-style beer with a toasted aroma and flavor, it has an intense and robust body on the palate with a medium bitterness. The Andes Origen Negra, as a beer of delight, harmonizes its slight acidity and bitterness with a soft sweetness.",
        "types": "cerveza",
        "brand": "Andes ",
        "calification": "0",
        "discount": "35",
        "origin": "Argentina",
        "alcohol": "5.3",
    },
    {
        "name": "Temple Scottish",
        "stock": "150",
        "img": "https://cepadevinos.com/wp-content/uploads/2021/01/7792798009350.jpg",
        "price": "650",
        "description": "Bottle 473 CC, Andes Origen rescues the pleasure of the moment. A beer designed for those people who value their free time, for those who enjoy the little moments in life. The ideal option for those who want to pamper themselves. Andes Negra is a German Schwarzbier-style beer with a toasted aroma and flavor, it has an intense and robust body on the palate with a medium bitterness. The Andes Origen Negra, as a beer of delight, harmonizes its slight acidity and bitterness with a soft sweetness.",
        "types": "cerveza",
        "brand": "Temple",
        "calification": "0",
        "discount": "38",
        "origin": "Argentina",
        "alcohol": "5.5",
    },
    {
        "name": " Martini Rosso  ",
        "stock": "150",
        "img": "http://d3ugyf2ht6aenh.cloudfront.net/stores/001/901/459/products/martini-rosso-1l1-3506a85668ce4faf2716358008215395-640-0.webp",
        "price": "884",
        "description": "Bottle 1L , ",
        "types": "vermouth",
        "brand": "Martini",
        "calification": "0",
        "discount": "10",
        "origin": "Italia",
        "alcohol": "14",
    },
    {
        "name": " Campari  ",
        "stock": "150",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Campari_plhhej.jpg",
        "price": "2400",
        "description": "Bottle 750cc , ",
        "types": "vermouth",
        "brand": "Campari",
        "calification": "0",
        "discount": "30",
        "origin": "Italia",
        "alcohol": "11",
    },
    {
        "name": " Aperol  ",
        "stock": "150",
        "img": "https://cepadevinos.com/wp-content/uploads/2020/08/aperol.png",
        "price": "2400",
        "description": "Bottle 750cc , ",
        "types": "vermouth",
        "brand": "Aperol",
        "calification": "0",
        "discount": "30",
        "origin": "Argentina",
        "alcohol": "11",
    },
    {
        "name": " Fernet Branca  ",
        "stock": "150",
        "img": "https://cepadevinos.com/wp-content/uploads/2017/07/Fernet_Branca_750cc._wgdwts.jpg",
        "price": "2890",
        "description": "Bottle 750cc ,Fernet is a bitter alcoholic drink of the amaro type made from various types of herbs (myrrh, rhubarb, chamomile, cardamom and saffron, among others), which are macerated in grape alcohol, filtered and aged in oak barrels for a period that can be from six to twelve months. It has a dark color, an intense aroma and an alcohol content of 45 degrees. ",
        "types": "vermouth",
        "brand": "Branca",
        "calification": "0",
        "discount": "26",
        "origin": "Italia",
        "alcohol": "11",
    },
    {
        "name": "Vaso Denver 343ml - Set X6",
        "stock": "100",
        "img": "https://d3ugyf2ht6aenh.cloudfront.net/stores/001/179/454/products/denver-bajo1-34d9c92b6a7170e6c716233358648860-1024-1024.jpg",
        "price": "21558",
        "description": "Whiskey glass, water, soda and drinks Measurements Height: 10 cm Diameter: 8cm Capacity: 343 ml 100% Crystalline Glass",
        "types": "cristaleria",
        "brand": "Denver",
        "calification": "0",
        "discount": "30",
        "origin": "Argentina",
    },
    {
        "name": "Cyrus long drink glasses",
        "stock": "100",
        "img": "https://volfar.vtexassets.com/arquivos/ids/407667-600-auto?v=1759436758&width=600&height=auto&aspect=true",
        "price": "21558",
        "description": "The Cyrus long drink glass is ideal for presenting your cocktails with style. It has a carved design that will highlight all your favorite drinks. Its capacity is 423 ml and it comes in a set of 6 units. Measurements: Mouth diameter: 7.5 cm. Height: 15 cm.",
        "types": "cristaleria",
        "brand": "Cyrus",
        "calification": "0",
        "discount": "30",
        "origin": "Argentina",
    },
    {
        "name": "Cabernet glasses 550 ml",
        "stock": "100",
        "img": "https://volfar.vtexassets.com/arquivos/ids/406013-800-auto?v=638085219178500000&width=800&height=auto&aspect=true",
        "price": "29940",
        "description": "Cabernet glasses 550 ml Skyline Set x6 Total height: 26 cm. Mouth diameter: 6 cm. High stem: 12.5 cm..",
        "types": "cristaleria",
        "brand": "Deli",
        "calification": "0",
        "discount": "30",
        "origin": "Argentina",
    },
    {
        "name": "Extra Slim Glasses 530 ml",
        "stock": "100",
        "img": "https://volfar.vtexassets.com/arquivos/ids/404189-800-auto?v=638076754698800000&width=800&height=auto&aspect=true",
        "price": "9773",
        "description": "Divine set of 6 glasses. The design of the extra-thin glass is ideal for drinking juices, soft drinks or drinks. It has a capacity of 530 ml. Measurements: Diameter: 8.9 cm. Height: 12.1 cm.",
        "types": "cristaleria",
        "brand": "Vicrila",
        "calification": "0",
        "discount": "30",
        "origin": "Argentina",
    },
]

module.exports = jsonProducts;